name: Check Code Formatting
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, review_requested]
    paths:
    - '**.h'
    - '**.cpp'

# jobs:
  # check_clang_format:
  #     name: Check clang-format
  #     runs-on: ubuntu-latest
  #     steps:
  #         - uses: actions/checkout@v1
  #         - uses: DoozyX/clang-format-lint-action@v0.5
  #         with:
  #             source: '.'
  #             # Our tutorials have special formatting, skip them
  #             exclude: './tutorial'
  #             extensions: 'h,cpp'
  #             clangFormatVersion: 9

jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu GCC LLVM8",
            os: ubuntu-18.04,
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            llvm_url: "https://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz"
          }
        - {
            name: "Ubuntu GCC LLVM9",
            os: ubuntu-18.04,
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            llvm_url: "https://releases.llvm.org/9.0.0/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz"
          }
        - {
            name: "Ubuntu Clang LLVM9",
            os: ubuntu-18.04,
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            llvm_url: "https://releases.llvm.org/9.0.0/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz"
          }
        - {
            name: "OSX LLVM9",
            os: macos-latest,
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            llvm_url: "https://releases.llvm.org/9.0.0/clang+llvm-9.0.0-x86_64-darwin-apple.tar.xz"
          }
        # - {
        #     name: "Windows Latest MSVC", artifact: "Windows-MSVC.tar.xz",
        #     os: windows-latest,
        #     build_type: "Release", cc: "cl", cxx: "cl",
        #     environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
        #   }
        # - {
        #     name: "Windows Latest MinGW", artifact: "Windows-MinGW.tar.xz",
        #     os: windows-latest,
        #     build_type: "Release", cc: "gcc", cxx: "g++"
        #   }

    steps:
    - uses: actions/checkout@v1

    - name: Download LLVM & Other
      shell: cmake -P {0}
      run: |
        # Download the right llvm release. Use CMake (rather than wget) because
        # we know it's available and will get the job done.
        file(DOWNLOAD "${{matrix.config.llvm_url}}" ./llvm-project.tar.xz SHOW_PROGRESS)
        execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./llvm-project.tar.xz)
        # Get libpng for the tutorials and apps
        # sudo apt-get -y --force-yes install libpng-dev
        # For generating docs
        # sudo apt-get -y --force-yes --no-install-recommends install doxygen

    - name: Configure CMake
      shell: cmake -P {0}
      run: |
        set(ENV{CC} "${{ matrix.config.cc }}")
        set(ENV{CXX} "${{ matrix.config.cxx }}")

        string(REGEX REPLACE
          "http[s]*://releases.llvm.org/([0-9][0-9]*)\\.([0-9]).*"
          "\\1\\2"
          LLVM_VERSION_NO_DOT
          "${{matrix.config.llvm_url}}"
        )

        execute_process(
          COMMAND ${CMAKE_COMMAND}
            -S .
            -B build
            -DCMAKE_BUILD_TYPE=Release
            -DHALIDE_REQUIRE_LLVM_VERSION="${LLVM_VERSION_NO_DOT}"
            -DLLVM_DIR="./llvm-project/lib/cmake/llvm/"
            -G "Unix Makefiles"
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()

    - name: Build Halide
      shell: cmake -P {0}
      run: |
        execute_process(
          COMMAND ${CMAKE_COMMAND} --build build
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()

    - name: Run Tests
      run: |
        cd build
        make -j4 run_tests

    # build-windows:
    #   runs-on: ${{ matrix.os }}
    #   strategy:
    #     matrix:
    #       os: [windows-latest, windows-2016]

    #   steps:
    #   - uses: actions/checkout@v1
    #   - name: configure
    #     run: mkdir build && cd build && cmake ..
    #   - name: build
    #     run: cmake --build build --config Debug
    #   - name: test
    #     run: cd build && ctest
