name: Check Code Formatting
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, review_requested]
    paths:
    - '**.h'
    - '**.cpp'

jobs:
  build:
    name: Check clang-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: '.'
        exclude: './tutorial'
        extensions: 'h,cpp'
        clangFormatVersion: 9
